obsservability name changes
terraform-ibm-modules/terraform-ibm-observability-agents pull request #237
Opened 2023-11-30 03:18 UTC by mounika-nalla

### Description

Updated varibale names with logdna and sysdig to log_analysis and cloud_monitoring respectively.

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [x] Major release (`X.x.x`)

##### Release notes content
As the helm chart's location relies on the directory name, and considering we are renaming the directories, this change will be a major release

```
  log_analysis_chart_location         = "${path.module}/chart/log-analysis-agent"
  cloud_monitoring_chart_location = "${path.module}/chart/cloud-monitoring-agent"
```

Changes made are as follows:

sysdig-agent directory renamed to cloud-monitoring-agent
logdna-agent directory renamed to log-analysis-agent
sysdig_instance -> cloud_monitoring_instance
sysdig_enabled -> cloud_monitoring_enabled
sysdig_instance_name -> cloud_monitoring_instance_name
sysdig_resource_group_id -> cloud_monitoring_resource_group_id
sysdig_access_key -> cloud_monitoring_access_key
sysdig_chart_location -> cloud_monitoring_chart_location
sysdig_agent_registry -> cloud_monitoring_agent_registry
sysdig_agent_namespace -> cloud_monitoring_agent_namespace
sysdig_key_validate_condition -> cloud_monitoring_key_validate_condition
sysdig_key_validate_msg -> cloud_monitoring_key_validate_msg
sysdig_key_validate_check -> cloud_monitoring_key_validate_check
sysdig_agent_tags -> cloud_monitoring_agent_tags
sysdig_agent -> cloud_monitoring_agent
sysdig_agent_version -> cloud_monitoring_agent_version
sysdig_metrics_filter -> cloud_monitoring_metrics_filter
sysdig_add_cluster_name -> cloud_monitoring_add_cluster_name
logdna_agent -> log_analysis_agent 
logdna-agent -> log-analysis-agent
logdna_instance_name -> log_analysis_instance_name
logdna_instance -> log_analysis_instance
logdna_agent_version -> log_analysis_agent_version
logdna_add_cluster_name -> log_analysis_add_cluster_name
logdna_ingestion_key -> log_analysis_ingestion_key
logdna_enabled -> log_analysis_enabled
logdna_agent_custom_line_exclusion -> log_analysis_agent_custom_line_exclusion
logdna_agent_custom_line_inclusion -> log_analysis_agent_custom_line_inclusion
logdna_agent_tags -> log_analysis_agent_tags
logdna_key_validate_check -> log_analysis_key_validate_check
logdna_key_validate_msg -> log_analysis_key_validate_msg
logdna_key_validate_condition -> log_analysis_key_validate_condition
logdna_agent_registry -> log_analysis_agent_registry
logdna_agent_namespace -> log_analysis_agent_namespace
logdna_resource_group_id -> log_analysis_resource_group_id
logdna_chart_location -> log_analysis_chart_location
logdna_secret_name -> log_analysis_secret_name

 

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

2023-11-30 14:53 UTC, mounika-nalla commented
/run pipeline

2023-11-30 15:10 UTC, mounika-nalla commented
/run pipeline

2023-11-30 17:42 UTC, mounika-nalla commented
/run pipeline

2023-12-11 17:06 UTC, mounika-nalla commented
/run pipeline

2023-12-11 17:13 UTC, mounika-nalla commented
/run pipeline

2023-12-12 18:13 UTC, ocofaigh requested changes
I think we went too far here. We should not be changing anything inside the charts. Just input variables and documentation

2023-12-12 18:13 UTC, ocofaigh commented on README.md
> +- name: LOG_ANALYSIS_K8S_METADATA_LINE_INCLUSION
This actually should be `LOGDNA_K8S_METADATA_LINE_INCLUSION` - please change it back

2023-12-12 18:13 UTC, ocofaigh commented on README.md
> +- name: LOG_ANALYSIS_K8S_METADATA_LINE_EXCLUSION
This actually should be `LOGDNA_K8S_METADATA_LINE_EXCLUSION` - please change it back

2023-12-12 18:17 UTC, ocofaigh commented
Also this should not be a breaking change and we should not skip the upgrade test. Please include the text `UNSKIP UPGRADE TEST` in the next commit

2023-12-13 16:20 UTC, mounika-nalla commented
/run pipeline

2023-12-14 12:36 UTC, ocofaigh commented
We probably need to use moved blocks to avoid this destroy:
```
Messages:   	Resource(s) identified to be destroyed 
        	            	Name: logdna_agent
        	            	Address: module.observability_agents.helm_release.logdna_agent[0]
        	            	Actions: [delete]
```

2023-12-15 02:53 UTC, mounika-nalla commented
> We probably need to use moved blocks to avoid this destroy:
> 
> ```
> Messages:   	Resource(s) identified to be destroyed 
>         	            	Name: logdna_agent
>         	            	Address: module.observability_agents.helm_release.logdna_agent[0]
>         	            	Actions: [delete]
> ```

Despite having the moved.tf, upgrade tests failed in my local. I noticed that when I execute `terraform state mv` for the resources (logdna_agent, sysdig_agent), the upgrade tests passed. However, having the moved blocks didn't yield the same outcome.

2023-12-15 02:53 UTC, mounika-nalla commented
/run pipeline

2023-12-15 22:34 UTC, mounika-nalla commented
/run pipeline

2023-12-18 15:13 UTC, mounika-nalla commented
/run pipeline

2023-12-18 20:12 UTC, toddgiguere approved these changes

2023-12-19 09:50 UTC, ocofaigh approved these changes

2023-12-19 09:50 UTC, merged

2023-12-19 09:52 UTC, terraform-ibm-modules-ops commented
:tada: This PR is included in version 1.16.0 :tada:

The release is available on [GitHub release](https://github.com/terraform-ibm-modules/terraform-ibm-observability-agents/releases/tag/v1.16.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: